### ISSUE TITLE
Uncheck "Always open files in a new window" and double-click to open the video file. iina will collapse.

### ISSUE THREAD

**Issue by ayurnero** [svobs/iina-advance#1]
Version 1.0 Uncheck "Always open files in a new window" and double-click to open the video file. iina will collapse.
Looking forward to your next version, and hope more people like this version.

**Comment by ayurnero** [comment]
If it is convenient, can you add a "maximized (with black border)" opening mode? Currently it can only be opened to fit the screen size (without black borders).

**Comment by svobs** [comment]
> Version 1.0 Uncheck "Always open files in a new window" and double-click to open the video file. iina will collapse.

Fixed in 308e1fc8ad24651a866396c23dfcc3bcd2c43177. I'm going to leave this issue open until I publish the next release. There are still a few issues which I want to fix but I hope to have the release ready in the next 1-2 weeks.

> If it is convenient, can you add a "maximized (with black border)" opening mode? Currently it can only be opened to fit the screen size (without black borders).

Oh yes. Seems like people who unlock the window size would prefer that behavior. Will change that.

**Comment by ayurnero** [comment]
> > Version 1.0 Uncheck "Always open files in a new window" and double-click to open the video file. iina will collapse.
> 
> Fixed in [308e1fc](https://github.com/svobs/iina-advance/commit/308e1fc8ad24651a866396c23dfcc3bcd2c43177). I'm going to leave this issue open until I publish the next release. There are still a few issues which I want to fix but I hope to have the release ready in the next 1-2 weeks.
> 
> > If it is convenient, can you add a "maximized (with black border)" opening mode? Currently it can only be opened to fit the screen size (without black borders).
> 
> Oh yes. Seems like people who unlock the window size would prefer that behavior. Will change that.

Thank you for your patient answers and hard work.

**Comment by svobs** [comment]
Just posted the 1.1 release! Of course it took a lot longer than expected, but there was a huge number of changes and a lot of small things to fix. Let me know of any new issues that appear!

**Comment by ayurnero** [comment]
> Just posted the 1.1 release! Of course it took a lot longer than expected, but there was a huge number of changes and a lot of small things to fix. Let me know of any new issues that appear!

Thank you, I have been looking forward to it for a long time!
